### ISSUE TITLE
Drop rustc-serialize dependency

### ISSUE THREAD

**Issue by dtolnay** [rsolomo/hipchat-client#6]
It has been deprecated: [announcement](https://users.rust-lang.org/t/deprecation-of-rustc-serialize/10485?u=dtolnay).

Is there any functionality you would require from Serde or another library before this would be possible?

**Comment by rsolomo** [comment]
I think Serde in it's current form should be able to work fine as a replacement for rustc-serialize in this library.

**Comment by rsolomo** [comment]
Resolved by #7
